name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    name: Create semantic release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          persist-credentials: false

      - name: Setup node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af

      - name: Create tag and GitHub release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
