name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    name: Create semantic release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
        with:
          persist-credentials: false

      - name: Setup node.js
        uses: actions/setup-node@7c29869aec4da703a571b27bcd84d4f15af0b56e

      - name: Create tag and GitHub release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
